### ISSUE TITLE
deleteBranch doesn't work

### ISSUE THREAD

**Issue by cdupuis** [atomist/artifact-source#43]
```
07/28 10:56:16.953 [command-handler-pool-3] ERROR [5f6e6d2f-b863-452c-9ddd-6b721e701ff3::atomist::lifecycle-rugs::T095SFFBK::C5XTP0893] c.a.r.f.g.p.DeleteBranchFunction - Failed to delete branch `delete-github-branch`
com.atomist.source.git.DoNotRetryException: HTTP/1.1 422 Unprocessable Entity
    at com.atomist.source.git.github.GitHubServices$$anonfun$com$atomist$source$git$github$GitHubServices$$httpRequest$1.apply(GitHubServices.scala:558)
    at com.atomist.source.git.github.GitHubServices$$anonfun$com$atomist$source$git$github$GitHubServices$$httpRequest$1.apply(GitHubServices.scala:553)
    at scalaj.http.HttpRequest$$anonfun$toResponse$3.apply(Http.scala:388)
    at scalaj.http.HttpRequest$$anonfun$toResponse$3.apply(Http.scala:380)
    at scala.Option.getOrElse(Option.scala:121)
    at scalaj.http.HttpRequest.toResponse(Http.scala:380)
    at scalaj.http.HttpRequest.scalaj$http$HttpRequest$$doConnection(Http.scala:360)
    at scalaj.http.HttpRequest.exec(Http.scala:335)
    at com.atomist.source.git.github.GitHubServices.com$atomist$source$git$github$GitHubServices$$httpRequest(GitHubServices.scala:553)
    at com.atomist.source.git.github.GitHubServices$$anonfun$deleteBranch$1.apply$mcV$sp(GitHubServices.scala:126)
    at com.atomist.source.git.github.GitHubServices$$anonfun$deleteBranch$1.apply(GitHubServices.scala:126)
    at com.atomist.source.git.github.GitHubServices$$anonfun$deleteBranch$1.apply(GitHubServices.scala:126)
    at scala.util.Try$.apply(Try.scala:192)
    at com.atomist.source.git.Retry$.retry(Retry.scala:30)
    at com.atomist.source.git.github.GitHubServices.deleteBranch(GitHubServices.scala:125)
    at com.atomist.rug.function.github.pullrequest.DeleteBranchFunction.invoke(DeleteBranchFunction.scala:30)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.atomist.rug.spi.AnnotatedRugFunction$class.run(AnnotatedRugFunction.scala:66)
    at com.atomist.rug.function.github.pullrequest.DeleteBranchFunction.run(DeleteBranchFunction.scala:13)
    at com.atomist.rug.runtime.plans.LocalInstructionRunner$$anonfun$2.apply(LocalInstructionRunner.scala:51)
```

**Comment by cdupuis** [comment]
@alankstewart could you take a look at that please. seems to be a regression.

**Comment by alankstewart** [comment]
Fixed by change in github-rugs
